#!/usr/bin/env python

import sys
import re


def get_replace_char(ftype):
    if ftype in ('pt', 'xml', 'zcml', 'html'):
        return '  '

    if ftype in ('py'):
        return '    '

if __name__ == '__main__':
    assert len(sys.argv) >= 2, "inline_expand requires input file path"
    fname = sys.argv[1]
    for fname in sys.argv[1:]:
        ext = fname.split('.')[-1]
        ftype = get_replace_char(ext)
        if not ftype:
            print "Not recognized type %s, extension %s" % (ftype, ext)
            continue
        fdata = open(fname, 'rb').read()
        fdata = fdata.replace('\t', ftype)
        fdata = fdata.replace('\r\n', '\n')
        out_data = []
        for line in fdata.split('\n'):
            out_data.append(re.sub(r'\s*$', '', line))
        fdata = "\n".join(out_data)
        out = open(fname, 'wb')
        out.write(fdata)
        print "processed file %s" % fname
        out.close()
